#!/user/bin/env fish
session=(find ~/code -mindepth 1 -maxdepth 2 -type -d)
session_name=(basename "$session")

if ! tmux has-session -t "$session_name"; then
    tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
