return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
        "html-lsp",
        "css-lsp",
        "tailwindcss-language-server",
        "ansible-language-server",
        "bash-language-server",
        "dockerfile-language-server",
        "eslint_d",
        "json-lsp",
        "marksman",
        "solargraph",
        "terraform-ls",
        "yaml-language-server",
        "omnisharp",
        "elixir-ls",
        "ansible-lint",
        "ruff-lsp",
        "prettierd",
      },
    },
  },
}
