#!/bin/sh

# This script will install homebrew and ansible

# Install homebrew if it is not installed already
if test ! "$(which brew)"; then
	echo "Installing homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

	(echo echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >>~/.zprofile
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Upgrade
brew upgrade

# Install ansible
brew install ansible

# Run ansible
ansible-playbook local.yml --ask-vault-pass --ask-become-pass
